### PR TITLE
cwtool with node requirement

### PR DESCRIPTION
**Pull request by johnbradley**
Removes cwlref-runner and creates new environment module `cwltool` with node support based on a new environment module.
cwltool sometimes requires node to handle javascript interpretation.
Also had an issue with ruamel.yaml missing `__init__.py` in the `ruamel` directory.
See https://bitbucket.org/ruamel/yaml/issues/8/unable-to-import-ruamelyaml-after

### CODE REVIEW

**Review by dleehr — CHANGES_REQUESTED** [review]
A couple of notes:

This a new spec file with **gcb02**, in addition to the (presumably broken) spec file from #13. What's the reason for that?  I don't think we have any other **gcb02** specs, so this would be a new convention, and it would leave a broken module out there.

The versioning is ambiguous. This spec installs `cwlref-runner` 1.0 with pip, but that package hasn't been updated in 2 years. It just [installs the current cwltool](https://github.com/common-workflow-language/cwltool/blob/master/cwlref-runner/setup.py#L20), so it would be hard to document exactly what version of cwltool we intended.

Looking forward, we'd probably like to provide newer versions of cwltool but wouldn't have a consistent way to version them.

I think we'd be better off with a cwltool module, since that would work better with module versioning.

**Comment by johnbradley** [comment]
__gcb02__ is just following the helmod conventions for creating an updated module of the same version of software. For example we have `zlib-1.2.8-fasrc07.spec` in our helmod repo. So there have been 7 modules created for the 1.2.8 version of zlib.

See The section https://github.com/Duke-GCB/helmod/blob/master/doc/HOWTO.md#prepare

**Comment by dleehr** [comment]
Thanks for clarifying the gcb02, that makes sense. But I think a cwltool module with a real version is a better way to go.

**Review by dleehr — APPROVED** [review]
LGTM

**Pull request merged**
